# Generated by Django 4.2.7 on 2023-12-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
