# Generated by Django 4.2.7 on 2023-12-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('c', 'copyright'), ('p', 'public content')], max_length=1),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
